### ISSUE TITLE
SAI interface does not consistent with sonic-sairedis

### ISSUE THREAD

**Issue by rogerho** [Azure/sonic-nas-ndi#8]
In SONiC Architecture document, the presentation should point out that NAS and Switch State Services use same SAI API version.
In current SONiC project, sonic-sairedis uses **create_vlan_member, remove_vlan_member** for VLAN member management,  but sonic-nas-ndi uses **add_ports_to_vlan, remove_ports_from_vlan**

**Comment by c-wichmann** [comment]
We are looking to move to the SAI 1.0 spec.

The Add VLAN member was a new to the SAI something after what we considered 0.94 and therefore wasn't used in the nas-ndi-api.

**Comment by rogerho** [comment]
OK, thanks

**Comment by rogerho** [comment]
In https://github.com/Broadcom-Switch/SAI , the implementation still use add_ports_to_vlan, remove_ports_from_vlan. 
How you verify NAS with Broadcom  chip, if you are looking to move to the SAI 1.0 spec ?
